# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RestFulApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Alamofire'
  pod 'RxSwift'
  # Pods for RestFulApp
  
  target 'RestFulAppTests' do
  end
  
  target 'RestFulAppUITests' do
    # Pods for testing
  end
  
end
