# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '12.0'
use_frameworks!

target 'RealmProj2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Realm'
  pod 'RealmSwift'
  # Pods for RealmProj2

  target 'RealmProj2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RealmProj2UITests' do
    # Pods for testing
  end

end
