# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '12.0'
use_frameworks!

target 'realmTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Realm'
  pod 'RealmSwift'
  # Pods for realmTest

  target 'realmTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'realmTestUITests' do
    # Pods for testing
  end

end
